version: '3.7'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGO_INITDB_DATABASE=sample_db
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./data:/data/db
    ports:
      - 27017:27017